# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Docker compose up
          command: docker-compose up -d

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/spock/
            mkdir -p ~/spock/classes/
            mkdir -p ~/spock/css/
            mkdir -p ~/spock/js/
            mkdir -p ~/spock/packages/
            find . -type f -regex ".*/build/reports/tests/test/index.html" -exec cp {} ~/spock/ \;
            find . -type f -regex ".*/build/reports/tests/test/classes/.*html" -exec cp {} ~/spock/classes/ \;
            find . -type f -regex ".*/build/reports/tests/test/css/.*css" -exec cp {} ~/spock/css/ \;
            find . -type f -regex ".*/build/reports/tests/test/js/.*js" -exec cp {} ~/spock/js/ \;
            find . -type f -regex ".*/build/reports/tests/test/packages/.*html" -exec cp {} ~/spock/packages/ \;
          when: always
      - store_test_results:
          path: ~/spock
      - store_artifacts:
          path: ~/spock